---
- hosts: all
  user: all
  vars:
    interface: "eth0"
    ipaddress: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"
    gateway: " {{hostvars[inventory_hostname]['ansible_default_ipv4']['gateway']}}"
    dns_servers: "8.8.8.8"
  tasks:
    - name: Configure static IP in  /etc/dhcpcd.conf
      become: yes
      lineinfile:
        dest:  /etc/dhcpcd.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: "^interface eth[0-9]$", line: "interface {{ interface }}" }
        - { regexp: "^static ip_address", line: "static ip_address={{ ipaddress }}/24" }
        - { regexp: "^static routers", line: "static routers={{ gateway }}" }
        - { regexp: "^static domain_name_servers", line: "static domain_name_servers={{ gateway }}, {{ dns_servers }}" }
 